"""add_org_digest_preferences_table

Revision ID: 77caa496e515
Revises: 9ff420d2e258
Create Date: 2026-03-07 12:11:43.692099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77caa496e515'
down_revision: Union[str, None] = '9ff420d2e258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_digest_preferences',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email_digest', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('digest_product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Product UUIDs to include. NULL = all accessible products.'),
    sa.Column('digest_timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('digest_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_digest_pref_user_org', 'org_digest_preferences', ['user_id', 'organization_id'], unique=True)
    op.create_index(op.f('ix_org_digest_preferences_organization_id'), 'org_digest_preferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_org_digest_preferences_user_id'), 'org_digest_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_org_digest_preferences_user_id'), table_name='org_digest_preferences')
    op.drop_index(op.f('ix_org_digest_preferences_organization_id'), table_name='org_digest_preferences')
    op.drop_index('ix_org_digest_pref_user_org', table_name='org_digest_preferences')
    op.drop_table('org_digest_preferences')
    # ### end Alembic commands ###
