"""add_team_contributor_summary_table

Revision ID: a176b3184ce7
Revises: 03095a74990f
Create Date: 2026-03-06 16:39:19.421499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a176b3184ce7'
down_revision: Union[str, None] = '03095a74990f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_contributor_summary',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('summaries', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('team_summary', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=False),
    sa.Column('total_contributors', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_contrib_summary_org_period', 'team_contributor_summary', ['organization_id', 'period'], unique=True)
    op.create_index(op.f('ix_team_contributor_summary_organization_id'), 'team_contributor_summary', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_contributor_summary_organization_id'), table_name='team_contributor_summary')
    op.drop_index('ix_team_contrib_summary_org_period', table_name='team_contributor_summary')
    op.drop_table('team_contributor_summary')
    # ### end Alembic commands ###
