"""Referral code model for the user-to-user referral system."""

import uuid as uuid_pkg
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Optional

from sqlalchemy import Column, DateTime, ForeignKey, Index, String, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from app.models.user import User


class ReferralCode(SQLModel, table=True):
    """
    Referral code for the user-based referral system.

    Each user can generate up to `user.invite_limit` codes.
    When a new user signs up with a code, both parties get 1 free month.

    Lifecycle:
    - Created: Code generated by owner
    - Redeemed: New user signed up with this code (redeemed_at + redeemed_by_user_id set)
    - Converted: Recipient added payment method (converted_at set, triggers sender reward)
    """

    __tablename__ = "referral_codes"
    __table_args__ = (
        Index("ix_referral_codes_user_id", "user_id"),
        Index("ix_referral_codes_code", "code", unique=True),
    )

    # Primary key
    id: uuid_pkg.UUID = Field(
        default_factory=uuid_pkg.uuid4,
        primary_key=True,
        nullable=False,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )

    # Owner (the user who created this referral code)
    user_id: uuid_pkg.UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
    )

    # The referral code (e.g., "SARAH-X7K9")
    code: str = Field(
        sa_column=Column(
            String(12),
            nullable=False,
            unique=True,
            comment="Unique referral code (e.g., SARAH-X7K9)",
        ),
    )

    # Timestamps
    created_at: datetime = Field(  # type: ignore[call-overload]
        default_factory=lambda: datetime.now(UTC),
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": text("now()")},
    )

    # Redemption tracking (when recipient signs up)
    redeemed_at: datetime | None = Field(  # type: ignore[call-overload]
        default=None,
        nullable=True,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"comment": "When code was used during sign-up"},
    )
    redeemed_by_user_id: uuid_pkg.UUID | None = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
            comment="User who redeemed this code",
        ),
    )

    # Conversion tracking (when recipient adds payment)
    converted_at: datetime | None = Field(  # type: ignore[call-overload]
        default=None,
        nullable=True,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"comment": "When recipient added payment (triggers sender reward)"},
    )

    # ─────────────────────────────────────────────────────────────────────────────
    # Relationships
    # ─────────────────────────────────────────────────────────────────────────────

    # Owner of this referral code
    owner: Optional["User"] = Relationship(
        back_populates="referral_codes",
        sa_relationship_kwargs={"foreign_keys": "[ReferralCode.user_id]"},
    )

    # User who redeemed this code (if any)
    redeemed_by: Optional["User"] = Relationship(
        sa_relationship_kwargs={"foreign_keys": "[ReferralCode.redeemed_by_user_id]"},
    )

    # ─────────────────────────────────────────────────────────────────────────────
    # Computed Properties
    # ─────────────────────────────────────────────────────────────────────────────

    @property
    def is_available(self) -> bool:
        """Code is available if not yet redeemed."""
        return self.redeemed_at is None

    @property
    def is_pending(self) -> bool:
        """Code is pending if redeemed but not converted."""
        return self.redeemed_at is not None and self.converted_at is None

    @property
    def is_converted(self) -> bool:
        """Code is converted if recipient added payment."""
        return self.converted_at is not None

    @property
    def status(self) -> str:
        """Return human-readable status."""
        if self.converted_at:
            return "converted"
        elif self.redeemed_at:
            return "pending"
        else:
            return "available"
