"""Team contributor summary model for AI-generated per-contributor narratives."""

import uuid as uuid_pkg
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import Column, DateTime, Index, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel


class TeamContributorSummary(SQLModel, table=True):
    """
    AI-generated per-contributor summaries, scoped to an organization + period.

    Stores a batch of contributor narratives generated by ContributorSummarizer,
    cached with a lazy-refresh model (6h warm / 48h stale / regenerate).

    This is a shared cache (not user-scoped) — one row per (org, period).
    """

    __tablename__ = "team_contributor_summary"
    __table_args__ = (
        Index(
            "ix_team_contrib_summary_org_period",
            "organization_id",
            "period",
            unique=True,
        ),
    )

    id: uuid_pkg.UUID = Field(
        default_factory=uuid_pkg.uuid4,
        primary_key=True,
        nullable=False,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )

    organization_id: uuid_pkg.UUID = Field(
        foreign_key="organizations.id",
        nullable=False,
        index=True,
    )

    period: str = Field(
        max_length=10,
        nullable=False,
        description="Time period: 7d, 14d, 30d",
    )

    # Batch result — keyed by contributor display_name
    # { "name": { "summary": str, "commit_count": int, "additions": int,
    #             "deletions": int, "commit_refs": [{"sha": str, "branch": str}] } }
    summaries: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSONB, nullable=False, server_default="{}"),
    )

    # Template-based team summary sentence
    team_summary: str = Field(default="", max_length=500)

    # Stats snapshot for smart-skip (don't regenerate if no new commits)
    total_commits: int = Field(default=0, nullable=False)
    total_contributors: int = Field(default=0, nullable=False)

    generated_at: datetime = Field(  # type: ignore[call-overload]
        default_factory=lambda: datetime.now(UTC),
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": text("now()")},
    )

    last_activity_at: datetime | None = Field(  # type: ignore[call-overload]
        default=None,
        nullable=True,
        sa_type=DateTime(timezone=True),
    )

    created_at: datetime = Field(  # type: ignore[call-overload]
        default_factory=lambda: datetime.now(UTC),
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": text("now()")},
    )

    updated_at: datetime = Field(  # type: ignore[call-overload]
        default_factory=lambda: datetime.now(UTC),
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": text("now()")},
    )
